First lab done
DariaWelt/Operating-Systems-labs pull request #1
Opened 2022-09-29 13:14 UTC by Sairsey

2022-09-29 14:43 UTC, DariaWelt requested changes
В ПР присутствует бинарник, его быть не должно. Программа пока не запускалась, так как класс не синглтон, и много правок по коду. Исправьте это, после будет проверяться работоспособность.

2022-09-29 14:43 UTC, DariaWelt commented on Parusov.Vladimir/lab1/main.cpp
> +      FILE *pidFile;
Лучше использовать std::fstream

2022-09-29 17:08 UTC, Sairsey commented on Parusov.Vladimir/lab1/check/file1
> +
Файлы и директории внутри директории "check" были добавлены чтобы вам было удобно тестировать работоспособность. Видимо у вас в этом нет необходимости, поэтому удаляю.

2022-09-29 17:33 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +    std::string pidFilePath = "/var/run/lab1.pid";
Убрал

2022-09-29 17:35 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +      char cleanDirPath[300];
Заменил на PATH_MAX

2022-09-29 17:36 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +    int DirExists(const char *path)
Исправил

2022-09-29 17:37 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +      else if(info.st_mode & S_IFDIR)
Если так, то тогда лучше:
return stat( path, &info ) == 0 &&
  (info.st_mode & S_IFDIR);
Хотелось логически выделить как именно работает данное API, но видимо не стоило. Исправил

2022-09-29 17:38 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +    Daemon(bool demonify, std::string configFilePath)
Отладчик теряет после демонификации процесс и нужно было как-то решать. Но если вам не нравится - убрал

2022-09-29 17:38 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +      char buf[300];
Заменил на PATH_MAX

2022-09-29 17:39 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +Daemon *Dimooooooon;
Момент с синглтоном проглядел. Исправил

2022-09-29 17:41 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +class Daemon
Момент с синглтоном проглядел. Исправил.
Но немного не по статье, я решил располагать его не на куче.

2022-09-29 17:44 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +#include <string>
Я понимаю что скорее всего первый сдаю, поэтому такое пристальное ревью, но прошу заметить значительная часть вопросов связана с Code-Style-ом в первую очередь, который обговорен не был заранее. Я конечно поправлю всё, но прошу выложить куда-нибудь ожидаемый код-стайл.
А на файлы я разбил

2022-09-29 17:47 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +    unsigned int sleepTime = 10;
Это было значение по умолчанию для времени ожидания между вызовами кода. Необходима если конфиг не является корректным, чтобы например не так быстро наполнять системный лог ненужной информацией. Но я добавил комментарий к этому

2022-09-29 17:50 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +    bool isRunning = true;
Вопрос скорее к стилю кодирования, но я исправлю

2022-09-29 17:52 UTC, Sairsey commented on Parusov.Vladimir/lab1/main.cpp
> +      FILE *pidFile;
В среднем стандартный C-style подход работает быстрее, но исправлю.

2022-10-01 08:14 UTC, DariaWelt requested changes
Программа в целом рабочая, сделайте небольшие исправления:

2022-10-01 08:14 UTC, DariaWelt commented on Parusov.Vladimir/lab1/daemon.cpp
> +        return;
Если этого числа нет, то конфиг считается невалидным и демон ничего не делает, хотя должно применяться дефолтное значение.

2022-10-01 08:33 UTC, DariaWelt commented on Parusov.Vladimir/lab1/main.cpp
> +#include <string>
Четких требований к code-style нет (название функций, констант, количество пробелов и тд). Ревью будет проходить намного быстрее, если придерживаться любого общепринятого cpp стиля (google, amazon, ...).

2022-10-01 08:37 UTC, DariaWelt commented on Parusov.Vladimir/lab1/main.cpp
> +      FILE *pidFile;
В данном случае работать быстрее не будет, а безопасность кода повысится при использовании STL. Это замечание - рекомендация. В следующие разы буду четче выделть комментарии-рекомендации от обязательных правок

2022-10-03 09:09 UTC, Sairsey commented on Parusov.Vladimir/lab1/daemon.cpp
> +        return;
Если я правильно вас понял, то ошибку я поправил

2022-10-03 09:09 UTC, Sairsey commented on Parusov.Vladimir/lab1/daemon.h
> +    Daemon() {}
Да, забыл добавить обработку конструктора и оператора. Исправил

2022-10-04 14:38 UTC, DariaWelt commented on Parusov.Vladimir/lab1/daemon.cpp
> +        return;
`m_isValidConfig`  не заменяется на true, из за этого конфиг без указания временного промежутка считается невалидным. 
В логе написано "not doing anything", что не отвечает ожидаемому поведению: использованию дефолтного времени. => программа не соответствует ТЗ.

2022-10-06 08:20 UTC, Sairsey commented on Parusov.Vladimir/lab1/daemon.cpp
> +        return;
Да, понял о чём вы. Поправил, теперь если время не удалось считать, будет применяться значение по умолчанию, а конфиг всё ещё считаться валидным.

2022-10-06 19:32 UTC, DariaWelt approved these changes

2022-10-06 19:35 UTC, merged