create daemon
DariaWelt/Operating-Systems-labs pull request #10
Opened 2022-10-24 11:49 UTC by diakozhh

2022-10-24 20:34 UTC, DariaWelt requested changes
Целевая ветка ПР неправильная, требуется вливать код в develop ветку.

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/daemon/daemon.cpp
> +        if((time_now - file_time) >= 180)
Опционально: две строки отличаются только в одном месте, поэтому можно сделать так:
```suggestion
std::filesystem::path destPath = std::filesystem::path(data.dst) / ((time_now - file_time) >= 180 ? subfolder_old : subfolder_new ) / entry.path().filename();
std::filesystem::copy_file(entry.path(), destPath, std::filesystem::copy_options::skip_existing); 
```

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/daemon/daemon.h
> +class Daemon {
Класс не синглтон

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/daemon/daemon.cpp
> +extern Daemon Daemon::instance;
`extern` не нужен

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/daemon/daemon.cpp
> +            int pid = 0;
```suggestion
            pid_t pid = 0;
```

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/config/config.h
> +    bool read(const std::string& path, Data& data);
Опционально:
Перенести метод в класс `Data`, раз уж он его принимает как один из параметров

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/daemon/daemon.cpp
> +        if((time_now - file_time) >= 180)
Непонятная константа `180`

2022-10-24 20:34 UTC, DariaWelt commented on Kozhevnikova.Diana/lab1/build.sh
> +cp $BUILD_DIR/$EXECUTABLE_NAME .
`BUILD_DIR` не удаляется

2022-10-24 22:36 UTC, diakozhh commented
Исправила замечания, кроме переноса read в Data, т.к., мне кажется, что структура здесь используется для группировки данных в конфига.

2022-10-25 07:54 UTC, DariaWelt approved these changes

2022-10-25 07:54 UTC, merged