Lab 1 Gabdushev Rushan (task #3)
DariaWelt/Operating-Systems-labs pull request #12
Opened 2022-10-25 23:02 UTC by maloxit

2022-10-26 18:19 UTC, DariaWelt requested changes

2022-10-26 18:36 UTC, maloxit commented on Gabdushev.Rushan/lab1/daemon.hpp
> +    const std::chrono::seconds defaultSleepTime = std::chrono::seconds(10);
С учетом строки выше выглядит логичнее оставить так.

2022-10-26 18:36 UTC, maloxit commented on Gabdushev.Rushan/lab1/daemon.cpp
> +static bool _dirExists(const char *path)
Исправил

2022-10-26 18:36 UTC, maloxit commented on Gabdushev.Rushan/lab1/daemon.cpp
> +void DaemonTmpCleaner::Initialize(std::string configLocalPath)
Исправил

2022-10-26 18:36 UTC, maloxit commented on Gabdushev.Rushan/lab1/daemon.cpp
> +    configAbsPath += "/" + configLocalPath;
Исправил

2022-10-26 18:37 UTC, maloxit commented on Gabdushev.Rushan/lab1/daemon.cpp
> +    syslog(LOG_INFO, "Sleep time set to %i seconds", (int)sleepTime.count());
Исправил

2022-10-27 10:57 UTC, DariaWelt approved these changes

2022-10-27 10:57 UTC, merged