lab1 Mordovin Nikolay
DariaWelt/Operating-Systems-labs pull request #13
Opened 2022-10-26 14:10 UTC by MordovinNik

12 вариант

2022-10-27 11:19 UTC, DariaWelt requested changes

2022-10-27 11:19 UTC, DariaWelt commented on Mordovin.Nikolay/lab1/daemon.cpp
> +    if (stat(path1.c_str(), &st1) == 0 && stat(path2.c_str(), &st2) == 0)
std::filesystem::is_directory

2022-10-27 11:19 UTC, DariaWelt commented on Mordovin.Nikolay/lab1/daemon.cpp
> +    std::vector<std::filesystem::__cxx11::path> filesToMove1, filesToMove2;
```suggestion
    std::vector<std::filesystem::path> filesToMove1, filesToMove2;
```

2022-10-27 11:19 UTC, DariaWelt commented on Mordovin.Nikolay/lab1/daemon.h
> +    void Init(const std::string configPath);
```suggestion
    void Init(const std::string& configPath);
```

2022-10-27 17:37 UTC, MordovinNik commented on Mordovin.Nikolay/lab1/daemon.cpp
> +    if (pid < 0)
Добавил логирование ошибок

2022-10-27 17:37 UTC, MordovinNik commented on Mordovin.Nikolay/lab1/daemon.cpp
> +    if (stat(path1.c_str(), &st1) == 0 && stat(path2.c_str(), &st2) == 0)
Исправил

2022-10-27 17:37 UTC, MordovinNik commented on Mordovin.Nikolay/lab1/daemon.cpp
> +    std::vector<std::filesystem::__cxx11::path> filesToMove1, filesToMove2;
Убрал

2022-10-27 17:38 UTC, MordovinNik commented on Mordovin.Nikolay/lab1/daemon.h
> +    void Init(const std::string configPath);
Исправил

2022-10-28 10:31 UTC, DariaWelt approved these changes

2022-10-28 10:32 UTC, merged