Lab 2
DariaWelt/Operating-Systems-labs pull request #15
Opened 2022-10-31 18:23 UTC by Sairsey

2022-11-16 20:34 UTC, DariaWelt requested changes
Программа работает. Исправьте замечания по коду

2022-11-17 18:50 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.h
> +    GUI *m_gui = nullptr;
Да, тут можно было бы воспользоваться умным указателем, но я посчитал что тут в этом необходимости нет

2022-11-17 18:54 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.h
> +    std::queue<Message> m_inputMessages;
Я конечно обернул, но не уверен что смысл в этом был

2022-11-17 18:54 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.cpp
> +bool Host::ConnectionClose(Connection *con, sem_t *sem_read, sem_t *sem_write)
Согласен, исправил

2022-11-17 18:54 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.cpp
> +#include <iostream>
Исправил

2022-11-17 18:55 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.cpp
> +  std::thread t(&Host::ConnectionWork, this);
Да, исправил

2022-11-17 19:12 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.cpp
> +  if (*sem_read == SEM_FAILED)
Можно, но я не захотел

2022-11-17 19:12 UTC, Sairsey commented on Parusov.Vladimir/lab2/host/host.cpp
> +    syslog(LOG_ERR, "An err %s", err.what());
Ага, поправил

2022-11-18 09:42 UTC, DariaWelt approved these changes

2022-11-18 09:43 UTC, merged