Baev_Daniil lab 1
DariaWelt/Operating-Systems-labs pull request #16
Opened 2022-11-05 19:42 UTC by BaevDaniil

2022-11-11 10:16 UTC, DariaWelt requested changes

2022-11-11 10:16 UTC, DariaWelt commented on Baev.Daniil/lab1/daemon.cpp
> +    std::regex commentFmt(R"(^\s*#.*\s*)"),
Код скопирован [отсюда](https://github.com/DariaWelt/Operating-Systems-labs/pull/3/files#:~:text=DaemonReminder%3A%3ALoadConfig). Перепишите

2022-11-16 09:48 UTC, BaevDaniil commented on Baev.Daniil/lab1/daemon.cpp
> +    Daemon::isTerminated = true;
Действительно я нахожусь уже в пространстве имен Daemon. Подобный синтаксис обусловлен стилем кода, если это можно так назвать. Пишу я так чтобы явно обозначить членов класса, что упрощает чтение кода поскольку сразу видно какие члены изменяются и вызываются. В простых методах это не так критично, но для единообразия я пишу так везде.

2022-11-16 09:48 UTC, BaevDaniil commented on Baev.Daniil/lab1/daemon.cpp
> +    std::regex commentFmt(R"(^\s*#.*\s*)"),
Что конкретно нужно переписать? Формат конфига? Метод его прочтения? Если речь про метод, то я слабо представляю, как можно по другому написать его (там же буквально цикл и три условия), используя регулярные выражения (составление которых является самой сложной частью этой функции).

2022-11-16 19:39 UTC, DariaWelt requested changes

2022-11-16 19:39 UTC, DariaWelt commented on Baev.Daniil/lab1/daemon.cpp
> +    Daemon::isTerminated = true;
Это плохая практика, которая сильно увеличивает код и делает его менее читаемым. Для этих целей имена членов класса начинают с `_` или `m_`.  Также есть места, в которых Вы не пользуетесь этим стилем.

2022-11-16 19:39 UTC, DariaWelt commented on Baev.Daniil/lab1/daemon.cpp
> +    std::regex commentFmt(R"(^\s*#.*\s*)"),
Перепишите целиком код демона. Придумайте другую структуру. Ваш файл и файл другого человека совпадают вплоть до названий функций, переменных и даже комментариев.

2022-11-16 19:40 UTC, DariaWelt commented on Baev.Daniil/lab1/daemon.cpp
> +    Daemon::isTerminated = true;
Это плохая практика, которая сильно увеличивает код и делает его менее читаемым. Для этих целей имена членов класса начинают с `_` или `m_`. Также есть места, в которых Вы не пользуетесь этим стилем.

2022-11-18 09:37 UTC, merged