Akhmetshin_Raul_lab1
DariaWelt/Operating-Systems-labs pull request #18
Opened 2022-11-24 15:00 UTC by Enoras

2022-12-01 22:47 UTC, DariaWelt requested changes
Программа работает. Внесите исправления, чтобы удовлетворить функциональным требованиям

2022-12-01 22:47 UTC, DariaWelt commented on Akhmetshin.Raul/lab1/daemon.cpp
> +        for (auto &file: fs::directory_iterator(directory)) {
Демон решает не ту задачу, которая поставлена в задании. Удалять содержимое необходимо если файл отсутствует. У Вас удалется, если присутствует dont.erase

2022-12-07 13:10 UTC, Enoras commented on Akhmetshin.Raul/lab1/daemon.cpp
> +        for (auto &file: fs::directory_iterator(directory)) {
исправил

2022-12-07 14:54 UTC, DariaWelt approved these changes

2022-12-07 14:56 UTC, merged