Add copying daemon
DariaWelt/Operating-Systems-labs pull request #2
Opened 2022-10-08 13:07 UTC by aVorotnikov

2022-10-08 21:09 UTC, DariaWelt requested changes
Сборка завершается ошибкой:
```
(base) daria@daria-0-1:~/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1$ sh build.sh 
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/build
[ 20%] Building CXX object CMakeFiles/copying_daemon.dir/main.cpp.o
[ 40%] Building CXX object CMakeFiles/copying_daemon.dir/copier/copier.cpp.o
[ 60%] Building CXX object CMakeFiles/copying_daemon.dir/daemon/daemon.cpp.o
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp: In function ‘void {anonymous}::Forking()’:
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:52:27: error: ‘STDIN_FILENO’ was not declared in this scope
   52 |     auto stdin_copy = dup(STDIN_FILENO);
      |                           ^~~~~~~~~~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:52:23: error: ‘dup’ was not declared in this scope
   52 |     auto stdin_copy = dup(STDIN_FILENO);
      |                       ^~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:53:28: error: ‘STDOUT_FILENO’ was not declared in this scope
   53 |     auto stdout_copy = dup(STDOUT_FILENO);
      |                            ^~~~~~~~~~~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:54:28: error: ‘STDERR_FILENO’ was not declared in this scope
   54 |     auto stderr_copy = dup(STDERR_FILENO);
      |                            ^~~~~~~~~~~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:56:16: error: ‘fork’ was not declared in this scope
   56 |     auto pid = fork();
      |                ^~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:65:9: error: ‘chdir’ was not declared in this scope
   65 |     if (chdir("/") < 0)
      |         ^~~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:70:26: error: ‘_SC_OPEN_MAX’ was not declared in this scope; did you mean ‘FOPEN_MAX’?
   70 |     for (int x = sysconf(_SC_OPEN_MAX); x >= 0; --x)
      |                          ^~~~~~~~~~~~
      |                          FOPEN_MAX
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:70:18: error: ‘sysconf’ was not declared in this scope; did you mean ‘swscanf’?
   70 |     for (int x = sysconf(_SC_OPEN_MAX); x >= 0; --x)
      |                  ^~~~~~~
      |                  swscanf
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:71:9: error: ‘close’ was not declared in this scope; did you mean ‘pclose’?
   71 |         close(x);
      |         ^~~~~
      |         pclose
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:73:5: error: ‘dup2’ was not declared in this scope
   73 |     dup2(stdin_copy, STDIN_FILENO);
      |     ^~~~
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp: In function ‘void {anonymous}::WritePid(const string&)’:
/home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:89:16: error: ‘getpid’ was not declared in this scope; did you mean ‘getpt’?
   89 |     pidFile << getpid();
      |                ^~~~~~
      |                getpt
make[2]: *** [CMakeFiles/copying_daemon.dir/build.make:104: CMakeFiles/copying_daemon.dir/daemon/daemon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/copying_daemon.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
cp: cannot stat 'build/copying_daemon': No such file or directory
```

2022-10-08 21:09 UTC, DariaWelt commented on .gitignore
> +# VS Code settings
Этот файл не должен лежать тут. Можно настроить локально игнор

2022-10-08 21:29 UTC, aVorotnikov commented on Vorotnikov.Andrey/lab1/daemon/daemon.cpp
> +        std::unique_lock lock(workMtx_);
Здесь мьютекс нужен для условной переменной. Чтобы была возможность сообщить функции `Run`, что обновилось состояние или завершилась работа. Данные он не защищает

2022-10-08 21:30 UTC, aVorotnikov commented on Vorotnikov.Andrey/lab1/copier/copier.cpp
> +    std::lock_guard lock(mtx_);
Вызов сигналов осуществляется асинхронно. Поэтому может возникнуть гонка - одновременно будет осуществляться копирование и загрузка нового конфига. Поэтому нужно обезопаситься от гонки данных

2022-10-08 21:41 UTC, aVorotnikov commented on Vorotnikov.Andrey/lab1/config/config.cpp
> +        copyInfoList.push_back(Copier::CopyInfo{splitted[0], splitted[1], splitted[2], splitted[3]});
Конкретно в этом случае это вряд ли имеет смысл - CopyInfo является C-ной структурой только для хранения данных, так что она не имеет конструктора. Поэтому в случае с `emplace_back` скорее всего будет move-конкструктор, который не отличается от применяемого здесь move-operaror=

2022-10-08 22:09 UTC, aVorotnikov commented
> Сборка завершается ошибкой:
> 
> ```
> (base) daria@daria-0-1:~/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1$ sh build.sh 
> -- The C compiler identification is GNU 9.4.0
> -- The CXX compiler identification is GNU 9.4.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/build
> [ 20%] Building CXX object CMakeFiles/copying_daemon.dir/main.cpp.o
> [ 40%] Building CXX object CMakeFiles/copying_daemon.dir/copier/copier.cpp.o
> [ 60%] Building CXX object CMakeFiles/copying_daemon.dir/daemon/daemon.cpp.o
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp: In function ‘void {anonymous}::Forking()’:
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:52:27: error: ‘STDIN_FILENO’ was not declared in this scope
>    52 |     auto stdin_copy = dup(STDIN_FILENO);
>       |                           ^~~~~~~~~~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:52:23: error: ‘dup’ was not declared in this scope
>    52 |     auto stdin_copy = dup(STDIN_FILENO);
>       |                       ^~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:53:28: error: ‘STDOUT_FILENO’ was not declared in this scope
>    53 |     auto stdout_copy = dup(STDOUT_FILENO);
>       |                            ^~~~~~~~~~~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:54:28: error: ‘STDERR_FILENO’ was not declared in this scope
>    54 |     auto stderr_copy = dup(STDERR_FILENO);
>       |                            ^~~~~~~~~~~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:56:16: error: ‘fork’ was not declared in this scope
>    56 |     auto pid = fork();
>       |                ^~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:65:9: error: ‘chdir’ was not declared in this scope
>    65 |     if (chdir("/") < 0)
>       |         ^~~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:70:26: error: ‘_SC_OPEN_MAX’ was not declared in this scope; did you mean ‘FOPEN_MAX’?
>    70 |     for (int x = sysconf(_SC_OPEN_MAX); x >= 0; --x)
>       |                          ^~~~~~~~~~~~
>       |                          FOPEN_MAX
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:70:18: error: ‘sysconf’ was not declared in this scope; did you mean ‘swscanf’?
>    70 |     for (int x = sysconf(_SC_OPEN_MAX); x >= 0; --x)
>       |                  ^~~~~~~
>       |                  swscanf
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:71:9: error: ‘close’ was not declared in this scope; did you mean ‘pclose’?
>    71 |         close(x);
>       |         ^~~~~
>       |         pclose
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:73:5: error: ‘dup2’ was not declared in this scope
>    73 |     dup2(stdin_copy, STDIN_FILENO);
>       |     ^~~~
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp: In function ‘void {anonymous}::WritePid(const string&)’:
> /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab1/daemon/daemon.cpp:89:16: error: ‘getpid’ was not declared in this scope; did you mean ‘getpt’?
>    89 |     pidFile << getpid();
>       |                ^~~~~~
>       |                getpt
> make[2]: *** [CMakeFiles/copying_daemon.dir/build.make:104: CMakeFiles/copying_daemon.dir/daemon/daemon.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/copying_daemon.dir/all] Error 2
> make: *** [Makefile:91: all] Error 2
> cp: cannot stat 'build/copying_daemon': No such file or directory
> ```

Видимо в разных версиях gcc по разному header'ы устроены. Извините, что так получилось

2022-10-09 10:18 UTC, DariaWelt requested changes
Добавьте, пожалуйста, в логирование работу демона. При загрузке невалидного конфига демон закрывается без сообщения в лог.

2022-10-09 10:18 UTC, DariaWelt commented on Vorotnikov.Andrey/lab1/copier/copier.cpp
> +    std::list<std::string> sources;
Этот лист нигде не изменяется и всегда пустой, поэтому функция всегда возвращает true

2022-10-09 10:50 UTC, aVorotnikov commented
Я немного не понял про логгирование. При загрузке некорректного лога в `/var/log/syslog` отображается:
```
Failed to update info from '/home/av/code/Operating-Systems-labs/Vorotnikov.Andrey/lab1/data/test.conf' config file
```
При корректном:
```
Config loaded
```
При некорректном конфиге демон продолжает работу со старым конфигом. Именно это неправильно? Надо завершать работу демона?

2022-10-09 11:20 UTC, DariaWelt commented
> Я немного не понял про логгирование. При загрузке некорректного лога в `/var/log/syslog` отображается:
> 
> ```
> Failed to update info from '/home/av/code/Operating-Systems-labs/Vorotnikov.Andrey/lab1/data/test.conf' config file
> ```
> 
> При корректном:
> 
> ```
> Config loaded
> ```
> 
> При некорректном конфиге демон продолжает работу со старым конфигом. Именно это неправильно? Надо завершать работу демона?

Если задать folder2 как невалидный путь, то конфиг считается валидным, начинается Copier::Copy(), и в ней std::filesystem::create_directory(dstDirPath) кидает исключение, которое не обрабатывается и демон схлопывается без сообщения в лог

2022-10-09 20:01 UTC, DariaWelt approved these changes

2022-10-09 20:03 UTC, merged