Baev Daniil lab2
DariaWelt/Operating-Systems-labs pull request #23
Opened 2022-12-12 19:49 UTC by BaevDaniil

2022-12-15 18:49 UTC, DariaWelt requested changes
```
[  4%] Built target host_fifo_autogen
[  8%] Building CXX object CMakeFiles/host_fifo.dir/host_fifo_autogen/mocs_compilation.cpp.o
[ 12%] Building CXX object CMakeFiles/host_fifo.dir/gui/gui.cpp.o
[ 16%] Building CXX object CMakeFiles/host_fifo.dir/host/clientHandler.cpp.o
[ 20%] Building CXX object CMakeFiles/host_fifo.dir/host/host.cpp.o
[ 25%] Building CXX object CMakeFiles/host_fifo.dir/client/client.cpp.o
/home/daria/CLionProjects/Operating-Systems-labs/Baev.Daniil/lab2/src/client/client.cpp: In member function ‘void Client::run()’:
/home/daria/CLionProjects/Operating-Systems-labs/Baev.Daniil/lab2/src/client/client.cpp:79:41: error: ‘getpid’ was not declared in this scope; did you mean ‘getpt’?
   79 |     syslog(LOG_INFO, "Client run %i\n", getpid());
      |                                         ^~~~~~
      |                                         getpt
make[2]: *** [CMakeFiles/host_fifo.dir/build.make:132: CMakeFiles/host_fifo.dir/client/client.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/host_fifo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
mv: cannot stat 'host*': No such file or directory
```

2022-12-15 23:10 UTC, DariaWelt requested changes
та же ошибка
/home/daria/CLionProjects/Operating-Systems-labs/Baev.Daniil/lab2/src/client/client.cpp:79:43: error: ‘getpid’ was not declared in this scope; did you mean ‘getpt’?

проверьте зависимости в файле

2022-12-16 00:10 UTC, BaevDaniil commented
Это очень странно. Действительно getpid() определен в unistd.h и он не включается в файл client.cpp. При этом никаких проблем с компиляцией на моей машине не было.

2022-12-16 11:17 UTC, DariaWelt approved these changes

2022-12-16 11:17 UTC, merged