Lab 1 Shvarts
DariaWelt/Operating-Systems-labs pull request #26
Opened 2022-12-21 12:50 UTC by AleksandrShvartz

2022-12-23 21:48 UTC, DariaWelt requested changes

2022-12-23 21:48 UTC, DariaWelt commented on Shvarts Aleksandr/lab1/script.sh
> +#!/bin/bash
файл по ТЗ должен называться build.sh

2022-12-23 21:48 UTC, DariaWelt commented on Shvarts Aleksandr/lab1/readme.md
> +Программа принимает в качестве единственного аргумента абсолютный путь до файла конфигурации. Этот файл должен быть текстовым и содержать внутри абсолютные пути до отслеживаемых папок, каждый путь на
Вместо этого файла с описанием поместите пример конфигурационного файла, даже если такой абсолютный путь существует только на Вашей машине.

2022-12-23 21:48 UTC, DariaWelt commented on Shvarts Aleksandr/lab1/readme.md
> +Программа принимает в качестве единственного аргумента абсолютный путь до файла конфигурации. Этот файл должен быть текстовым и содержать внутри абсолютные пути до отслеживаемых папок, каждый путь на
В ТЗ сказано:
>> Конфигурационный файл изначально лежит в рабочей папке при запуске, затем программа должна запоминать его абсолютный путь для дальнейшего использования.

2022-12-23 21:48 UTC, DariaWelt commented on Shvarts Aleksandr/lab1/Notify.h
> +#define EVENT_SIZE  ( sizeof (struct inotify_event) )
эти define замените на константы.

2022-12-24 02:37 UTC, AleksandrShvartz commented on Shvarts Aleksandr/lab1/script.sh
> +#!/bin/bash
Исправил

2022-12-24 02:38 UTC, AleksandrShvartz commented on Shvarts Aleksandr/lab1/readme.md
> +Программа принимает в качестве единственного аргумента абсолютный путь до файла конфигурации. Этот файл должен быть текстовым и содержать внутри абсолютные пути до отслеживаемых папок, каждый путь на
Добавил файл config.txt

2022-12-24 02:38 UTC, AleksandrShvartz commented on Shvarts Aleksandr/lab1/readme.md
> +Программа принимает в качестве единственного аргумента абсолютный путь до файла конфигурации. Этот файл должен быть текстовым и содержать внутри абсолютные пути до отслеживаемых папок, каждый путь на
Исправил

2022-12-24 02:38 UTC, AleksandrShvartz commented on Shvarts Aleksandr/lab1/Notify.h
> +#define EVENT_SIZE  ( sizeof (struct inotify_event) )
Заменил

2022-12-25 17:21 UTC, DariaWelt commented on Shvarts Aleksandr/lab1/script.sh
> +#!/bin/bash
Теперь этот файл дублирует build.sh. script.sh следует удалить

2022-12-26 02:09 UTC, AleksandrShvartz commented on Shvarts Aleksandr/lab1/script.sh
> +#!/bin/bash
Удалил script.sh

2022-12-26 17:45 UTC, merged