lab2 Akhmetshin R.I.
DariaWelt/Operating-Systems-labs pull request #28
Opened 2022-12-23 00:16 UTC by Enoras

2022-12-25 18:08 UTC, DariaWelt requested changes
При закрытии окна хоста процессы клиенты остаются запущенными, так быть не должно

2022-12-25 18:08 UTC, DariaWelt commented on Akhmetshin.Raul/lab2/host/wolf.cpp
> +    case SIGTERM: {
При завершении хоста все клиенты должны завершаться

2022-12-25 21:49 UTC, Enoras commented on Akhmetshin.Raul/lab2/CMakeLists.txt
> +foreach(CONN shm mq fifo)
Исправил

2022-12-25 21:50 UTC, Enoras commented on Akhmetshin.Raul/lab2/build.sh
> +for conn_type in "shm" "mq" "fifo"
Исправил

2022-12-25 21:50 UTC, Enoras commented on Akhmetshin.Raul/lab2/client/client.cpp
> +        std::cout << "Invalid arguments. Must be two args, second arg - host pid" << std::endl;
Исправил

2022-12-25 21:50 UTC, Enoras commented on Akhmetshin.Raul/lab2/connection/conn.h
> +    // std::string name;
убрал

2022-12-25 21:52 UTC, Enoras commented on Akhmetshin.Raul/lab2/host/wolf.cpp
> +    case SIGTERM: {
Исправил

2022-12-25 21:52 UTC, Enoras commented on Akhmetshin.Raul/lab2/model/semaphores.h
> +std::string const Semaphores::host_semaphore_name = "HostSemaphore";
std::string не работает с constexpr, во всяком случае в С++17.  Оставил без изменений

2022-12-26 17:49 UTC, DariaWelt approved these changes

2022-12-26 17:49 UTC, merged