Lab 2, Var 5, Vorotnikov Andrey
DariaWelt/Operating-Systems-labs pull request #31
Opened 2022-12-26 00:30 UTC by aVorotnikov

2022-12-26 20:08 UTC, DariaWelt requested changes
```
(base) daria@daria-0-1:~/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab2$ sh build.sh 
mkdir: cannot create directory ‘build’: File exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daria/CLionProjects/Operating-Systems-labs/Vorotnikov.Andrey/lab2/build
[  3%] Automatic MOC and UIC for target gui
[  3%] Built target gui_autogen
[  6%] Building CXX object host/gui/CMakeFiles/gui.dir/gui_autogen/mocs_compilation.cpp.o
[  9%] Building CXX object host/gui/CMakeFiles/gui.dir/src/gui.cpp.o
[ 12%] Linking CXX static library libgui.a
[ 12%] Built target gui
[ 16%] Building CXX object connections/CMakeFiles/connection_fifo.dir/src/conn.cpp.o
[ 19%] Building CXX object connections/CMakeFiles/connection_fifo.dir/src/conn_fifo.cpp.o
[ 22%] Linking CXX static library libconnection_fifo.a
[ 22%] Built target connection_fifo
[ 25%] Building CXX object game_rules/CMakeFiles/game_rules.dir/src/game_rules.cpp.o
[ 29%] Linking CXX static library libgame_rules.a
[ 29%] Built target game_rules
[ 32%] Building CXX object host/lib/CMakeFiles/host_lib.dir/src/host.cpp.o
[ 35%] Linking CXX static library libhost_lib.a
[ 35%] Built target host_lib
[ 38%] Building CXX object CMakeFiles/host_fifo.dir/host/src/main.cpp.o
[ 41%] Linking CXX executable host_fifo
/usr/bin/ld: host/lib/libhost_lib.a(host.cpp.o): undefined reference to symbol 'sem_close@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/host_fifo.dir/build.make:104: host_fifo] Error 1
make[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/host_fifo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
build.sh: 14: Syntax error: "(" unexpected
```

также могу сказать, что это не последняя ошибка сборки при линковке, нужно сделать больше чем 1 исправление для фикса

2022-12-26 20:08 UTC, DariaWelt commented on Vorotnikov.Andrey/lab2/build.sh
> +CONNS=("fifo" "mq" "seg")
при добавлении нового типа соединения пользователь должен иметь возможность запустить сборку без изменения скриптов сборки

2022-12-26 20:38 UTC, aVorotnikov commented on Vorotnikov.Andrey/lab2/build.sh
> +CONNS=("fifo" "mq" "seg")
На gcc9 теперь собирается

2022-12-27 07:11 UTC, DariaWelt approved these changes

2022-12-27 07:12 UTC, merged