Khripunkov Dmitry Lab1-15
DariaWelt/Operating-Systems-labs pull request #4
Opened 2022-10-11 20:54 UTC by ThinkingFrog

2022-10-13 16:52 UTC, DariaWelt requested changes
Программа работает. Нужно поправить сохранение пид файла и убрать лишние файлы. По желанию можно расширить логирование и сделать рефакторинг согласно замечаниям

2022-10-13 20:55 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/.clang-format
> +---
clang-format не связан с компилятором, это отдельный инструмент для форматирования, который даже кажется поставляется отдельно от компилятора clang

2022-10-13 21:04 UTC, DariaWelt commented on Khripunkov.Dmitry/lab1/.clang-format
> +---
Действительно. И все же он не нужен в ПР

2022-10-16 18:31 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/include/daemon.hpp
> +    const std::string proc_dir = "/proc";
Если делать через char*, то нет возможности делать легкую конкатенацию через operator+, а переменная в основном для этого и нужна. А в чём смысл делать конкретно это поле static?

2022-10-16 18:37 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/src/daemon.cpp
> +    f >> pid;
/var/run на современных системах это симлинк в /run, а запись в него требует sudo, иначе падает с permission denied. Если писать в корневую файловую систему, демона нельзя будет запустить не из-под sudo, это удовлетворительно для этой работы?

2022-10-17 17:16 UTC, DariaWelt commented on Khripunkov.Dmitry/lab1/include/daemon.hpp
> +    const std::string proc_dir = "/proc";
1. Где это нужно, можно создать от этой строки string и использовать конкатинацию
2. Это поле константное и одинаковое для всех экземпляров класса (хоть он тут и один)

2022-10-20 20:34 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/src/daemon.cpp
> +    f >> pid;
Сделал через создание и выставление 666 прав пид файлу при сборке

2022-10-20 20:35 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/src/daemon.cpp
> +    std::vector<std::time_t> last_modified_time;
Добавил

2022-10-20 20:36 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/include/config.hpp
> +namespace fs = std::filesystem;
Убрал в целом, плюсы кажется не позволяют на класс делать namespace, только на отдельную функцию

2022-10-20 20:36 UTC, ThinkingFrog commented on Khripunkov.Dmitry/lab1/include/config.hpp
> +#include <filesystem>
Добавил

2022-10-21 13:40 UTC, DariaWelt approved these changes

2022-10-21 13:42 UTC, merged