Faizrahmanov Artur lab1
DariaWelt/Operating-Systems-labs pull request #5
Opened 2022-10-17 07:18 UTC by Hembos

2022-10-17 15:39 UTC, DariaWelt requested changes

2022-10-17 15:39 UTC, DariaWelt commented on Faizrahmanov.Artur/lab1/main.cpp
> +    return 0;
Опционально:
Раз уж вверху используется EXIT_FAILURE, то можно
```suggestion
    return EXIT_SUCCESS;
```

2022-10-17 15:39 UTC, DariaWelt commented on Faizrahmanov.Artur/lab1/FileMoverDaemon.cpp
> +            std::string command = "rm -r " + std::filesystem::absolute(toPath).string() + "/*";
команда выполняется в отдельном процессе, неоправденнно теряется время на переключение контекста процессов. Использование system в коде в целом небезопасно и этого стоит избегать. Логику нужно реализовать средствами cpp. То же относится и к mv комманде

2022-10-18 09:13 UTC, Hembos commented on Faizrahmanov.Artur/lab1/FileMoverDaemon.cpp
> +        if (Config::getInstance()->isConfigReaded())
Так у меня же Config является синглтоном. Как я могу вызвать его методы в другом классе без получения инстанса?

2022-10-18 21:10 UTC, DariaWelt commented on Faizrahmanov.Artur/lab1/FileMoverDaemon.cpp
> +        if (Config::getInstance()->isConfigReaded())
Не увидела, что это другой класс. Тогда все верно

2022-10-21 15:47 UTC, DariaWelt requested changes
Программа работает, Сделайте ее поведение соответствующим ТЗ

2022-10-22 10:38 UTC, DariaWelt approved these changes

2022-10-22 10:38 UTC, merged